
package br.com.acaosistemas.predictionssoapclient;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PredictionsSOAP", targetNamespace = "http://predictionssoap.acaosistemas.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PredictionsSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.DeleteResponse")
    @Action(input = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/deleteRequest", output = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/deleteResponse")
    public String delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "create", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.Create")
    @ResponseWrapper(localName = "createResponse", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.CreateResponse")
    @Action(input = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/createRequest", output = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/createResponse", fault = {
        @FaultAction(className = VerbosityException.class, value = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/create/Fault/VerbosityException")
    })
    public String create(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws VerbosityException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.acaosistemas.predictionssoapclient.Prediction>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.GetAllResponse")
    @Action(input = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/getAllRequest", output = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/getAllResponse")
    public List<Prediction> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.acaosistemas.predictionssoapclient.Prediction
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOne", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.GetOne")
    @ResponseWrapper(localName = "getOneResponse", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.GetOneResponse")
    @Action(input = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/getOneRequest", output = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/getOneResponse")
    public Prediction getOne(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws VerbosityException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "edit", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.Edit")
    @ResponseWrapper(localName = "editResponse", targetNamespace = "http://predictionssoap.acaosistemas.com.br/", className = "br.com.acaosistemas.predictionssoapclient.EditResponse")
    @Action(input = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/editRequest", output = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/editResponse", fault = {
        @FaultAction(className = VerbosityException.class, value = "http://predictionssoap.acaosistemas.com.br/PredictionsSOAP/edit/Fault/VerbosityException")
    })
    public String edit(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws VerbosityException
    ;

}
