
package br.com.acaosistemas.helloclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloServicePortType", targetNamespace = "http://hello.acaosistemas.com.br")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloServicePortType {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "urn:echo")
    @WebResult(targetNamespace = "http://hello.acaosistemas.com.br")
    @RequestWrapper(localName = "echo", targetNamespace = "http://hello.acaosistemas.com.br", className = "br.com.acaosistemas.helloclient.Echo")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://hello.acaosistemas.com.br", className = "br.com.acaosistemas.helloclient.EchoResponse")
    public String echo(
        @WebParam(name = "name", targetNamespace = "http://hello.acaosistemas.com.br")
        String name);

}
