
package br.com.acaosistemas.temperatureconverterclient2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TempConvert", targetNamespace = "http://temperatureconverter.acaosistemas.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TempConvert {


    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod(operationName = "c2f")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "c2f", targetNamespace = "http://temperatureconverter.acaosistemas.com.br/", className = "br.com.acaosistemas.temperatureconverterclient2.C2F")
    @ResponseWrapper(localName = "c2fResponse", targetNamespace = "http://temperatureconverter.acaosistemas.com.br/", className = "br.com.acaosistemas.temperatureconverterclient2.C2FResponse")
    @Action(input = "http://temperatureconverter.acaosistemas.com.br/TempConvert/c2fRequest", output = "http://temperatureconverter.acaosistemas.com.br/TempConvert/c2fResponse")
    public float c2F(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns float
     */
    @WebMethod(operationName = "f2c")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "f2c", targetNamespace = "http://temperatureconverter.acaosistemas.com.br/", className = "br.com.acaosistemas.temperatureconverterclient2.F2C")
    @ResponseWrapper(localName = "f2cResponse", targetNamespace = "http://temperatureconverter.acaosistemas.com.br/", className = "br.com.acaosistemas.temperatureconverterclient2.F2CResponse")
    @Action(input = "http://temperatureconverter.acaosistemas.com.br/TempConvert/f2cRequest", output = "http://temperatureconverter.acaosistemas.com.br/TempConvert/f2cResponse")
    public float f2C(
        @WebParam(name = "arg0", targetNamespace = "")
        float arg0);

}
