
package br.com.acaosistemas.echoclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Echo", targetNamespace = "http://echo.acaosistemas.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Echo {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "echo", targetNamespace = "http://echo.acaosistemas.com.br/", className = "br.com.acaosistemas.echoclient.Echo_Type")
    @ResponseWrapper(localName = "echoResponse", targetNamespace = "http://echo.acaosistemas.com.br/", className = "br.com.acaosistemas.echoclient.EchoResponse")
    @Action(input = "http://echo.acaosistemas.com.br/Echo/echoRequest", output = "http://echo.acaosistemas.com.br/Echo/echoResponse")
    public String echo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
