
package br.com.acaosistemas.imageclientmtom;

import java.util.List;
import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SkiImageService", targetNamespace = "http://images.acaosistemas.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SkiImageService {


    /**
     * 
     * @return
     *     returns java.util.List<javax.activation.DataHandler>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImages", targetNamespace = "http://images.acaosistemas.com.br/", className = "br.com.acaosistemas.imageclientmtom.GetImages")
    @ResponseWrapper(localName = "getImagesResponse", targetNamespace = "http://images.acaosistemas.com.br/", className = "br.com.acaosistemas.imageclientmtom.GetImagesResponse")
    @Action(input = "http://images.acaosistemas.com.br/SkiImageService/getImagesRequest", output = "http://images.acaosistemas.com.br/SkiImageService/getImagesResponse")
    public List<DataHandler> getImages();

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.activation.DataHandler
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getImage", targetNamespace = "http://images.acaosistemas.com.br/", className = "br.com.acaosistemas.imageclientmtom.GetImage")
    @ResponseWrapper(localName = "getImageResponse", targetNamespace = "http://images.acaosistemas.com.br/", className = "br.com.acaosistemas.imageclientmtom.GetImageResponse")
    @Action(input = "http://images.acaosistemas.com.br/SkiImageService/getImageRequest", output = "http://images.acaosistemas.com.br/SkiImageService/getImageResponse")
    public DataHandler getImage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
